// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asegblxpnduuagqincnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzZWdibHhwbmR1dWFncWluY25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MzE1NDIsImV4cCI6MjA1ODEwNzU0Mn0.-6rnDKnZvsmXJVQKPlQ8hRl83gVZwyBF4yLnsAOmgFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);